export const effectiveDate = "14th September 2023"
export const companyName = "Vipul V. Patil"
export const companyAddress = "Mumbai"
export const companyJurisdiction = "India"
export const companyEmail = "assist.prospect@gmail.com"
