export const defaultCandidates = [
  {
    id: "hogwarts_1",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Hermione Granger\",\"Email\": \"hermione@email.com\",\"Phone\": \"+1 (234) 567-8901\",\"City\": \"London\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 5,\"Tech Skills\": [\"Charms\", \"Transfiguration\", \"Potion-making\", \"Research\", \"Library Skills\"],\"Soft Skills\": [\"Research\", \"Problem-solving\", \"Time Management\"],\"Recommended Roles\": [\"Ministry of Magic Researcher\", \"Hogwarts Professor\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1999\"},{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Advanced Studies\",\"CompletionYear\": \"2002\"}],\"Experience\": [{\"Title\": \"Ministry of Magic Researcher\",\"Company Name\": \"Ministry of Magic\",\"Starting Year\": \"2002\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Advanced Research Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_2",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Severus Snape\",\"Email\": \"snape@email.com\",\"Phone\": \"+1 (567) 890-1234\",\"City\": \"Spinner's End\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 20,\"Tech Skills\": [\"Potion-making\", \"Occlumency\", \"Legilimency\", \"Dueling\"],\"Soft Skills\": [\"Resourcefulness\", \"Dedication\", \"Subtlety\"],\"Recommended Roles\": [\"Potions Master at Hogwarts\", \"Occasional Spy\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1971\"}],\"Experience\": [{\"Title\": \"Potions Master\",\"Company Name\": \"Hogwarts School of Witchcraft and Wizardry\",\"Starting Year\": \"1981\",\"Ending Year\": \"1996\"},{\"Title\": \"Double Agent\",\"Company Name\": \"Order of the Phoenix / Death Eaters\",\"Starting Year\": \"1996\",\"Ending Year\": \"1997\"}],\"Certifications\": [\"Advanced Potions Mastery Certification\", \"Espionage Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_3",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Minerva McGonagall\",\"Email\": \"mcgonagall@email.com\",\"Phone\": \"+1 (789) 012-3456\",\"City\": \"Hogsmeade\",\"State\": \"Scotland\",\"Country\": \"United Kingdom\",\"YoE\": 30,\"Tech Skills\": [\"Transfiguration\", \"Animagus\", \"Leadership\"],\"Soft Skills\": [\"Teaching\", \"Discipline\", \"Fairness\"],\"Recommended Roles\": [\"Transfiguration Professor at Hogwarts\", \"Deputy Headmistress\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1947\"}],\"Experience\": [{\"Title\": \"Transfiguration Professor\",\"Company Name\": \"Hogwarts School of Witchcraft and Wizardry\",\"Starting Year\": \"1956\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Teaching Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_4",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Nymphadora Tonks\",\"Email\": \"tonks@email.com\",\"Phone\": \"+1 (345) 678-9012\",\"City\": \"London\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 5,\"Tech Skills\": [\"Metamorphmagus Abilities\", \"Auror Training\", \"Dueling\"],\"Soft Skills\": [\"Adaptability\", \"Sense of Humor\", \"Determination\"],\"Recommended Roles\": [\"Auror\", \"Order of the Phoenix Member\"],\"Education\": [{\"Institute\": \"Auror Training Academy\",\"Qualification\": \"Auror Certification\",\"CompletionYear\": \"2000\"}],\"Experience\": [{\"Title\": \"Auror\",\"Company Name\": \"Ministry of Magic\",\"Starting Year\": \"2000\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Auror Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_5",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Luna Lovegood\",\"Email\": \"luna@email.com\",\"Phone\": \"+1 (678) 901-2345\",\"City\": \"Ottery St. Catchpole\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 2,\"Tech Skills\": [\"Naturalist\", \"Thestrals Understanding\", \"Quibbler Contributor\"],\"Soft Skills\": [\"Creativity\", \"Open-mindedness\", \"Optimism\"],\"Recommended Roles\": [\"Magizoologist\", \"Quibbler Journalist\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1998\"}],\"Experience\": [{\"Title\": \"Magizoologist Assistant\",\"Company Name\": \"Wizarding Wildlife Conservation Society\",\"Starting Year\": \"1998\",\"Ending Year\": \"2000\"},{\"Title\": \"Quibbler Journalist\",\"Company Name\": \"The Quibbler\",\"Starting Year\": \"2001\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Magizoology Certification\", \"Journalism Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_6",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Albus Dumbledore\",\"Email\": \"dumbledore@email.com\",\"Phone\": \"+1 (456) 789-0123\",\"City\": \"Hogsmeade\",\"State\": \"Scotland\",\"Country\": \"United Kingdom\",\"YoE\": 50,\"Tech Skills\": [\"Advanced Wizardry\", \"Strategic Planning\", \"Mentorship\"],\"Soft Skills\": [\"Wisdom\", \"Leadership\", \"Calm under pressure\"],\"Recommended Roles\": [\"Headmaster at Hogwarts\", \"Advisor to the Ministry of Magic\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1858\"}],\"Experience\": [{\"Title\": \"Headmaster\",\"Company Name\": \"Hogwarts School of Witchcraft and Wizardry\",\"Starting Year\": \"1956\",\"Ending Year\": \"1997\"}],\"Certifications\": [\"Educational Leadership Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_7",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Harry Potter\",\"Email\": \"harrypotter@email.com\",\"Phone\": \"+1 (123) 456-7890\",\"City\": \"London\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 5,\"Tech Skills\": [\"Defence Against the Dark Arts\", \"Potion-making\", \"Quidditch\", \"Wizardry\"],\"Soft Skills\": [\"Leadership\", \"Teamwork\", \"Courage\"],\"Recommended Roles\": [\"Auror\", \"Defence Against the Dark Arts Professor\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"2000\"}],\"Experience\": [{\"Title\": \"Auror\",\"Company Name\": \"Ministry of Magic\",\"Starting Year\": \"2000\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Auror Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_8",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Fleur Delacour\",\"Email\": \"fleur@email.com\",\"Phone\": \"+1 (789) 012-3456\",\"City\": \"Shell Cottage\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 10,\"Tech Skills\": [\"Veela Abilities\", \"Wizardry\", \"Charm Magic\"],\"Soft Skills\": [\"Eloquence\", \"Grace\", \"Multilingualism\"],\"Recommended Roles\": [\"Charm Instructor at Beauxbatons Academy\", \"Translator\"],\"Education\": [{\"Institute\": \"Beauxbatons Academy of Magic\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1995\"}],\"Experience\": [{\"Title\": \"Charm Instructor\",\"Company Name\": \"Beauxbatons Academy of Magic\",\"Starting Year\": \"2005\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Charm Mastery Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_9",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Ginny Weasley\",\"Email\": \"ginny@email.com\",\"Phone\": \"+1 (567) 890-1234\",\"City\": \"Ottery St. Catchpole\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 5,\"Tech Skills\": [\"Quidditch\", \"Bat-Bogey Hex\", \"Dueling\", \"Journalism\"],\"Soft Skills\": [\"Determination\", \"Courage\", \"Team Player\"],\"Recommended Roles\": [\"Professional Quidditch Player\", \"Sports Journalist\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"2004\"}],\"Experience\": [{\"Title\": \"Professional Quidditch Player\",\"Company Name\": \"Holyhead Harpies\",\"Starting Year\": \"2004\",\"Ending Year\": \"2010\"},{\"Title\": \"Sports Journalist\",\"Company Name\": \"The Daily Prophet\",\"Starting Year\": \"2011\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Professional Quidditch Player License\", \"Journalism Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_10",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Sirius Black\",\"Email\": \"sirius@email.com\",\"Phone\": \"+1 (890) 123-4567\",\"City\": \"London\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 0,\"Tech Skills\": [\"Animagus\", \"Duelling\", \"Flying\"],\"Soft Skills\": [\"Loyalty\", \"Bravery\", \"Resourcefulness\"],\"Recommended Roles\": [\"Auror\", \"Member of the Order of the Phoenix\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1978\"}],\"Experience\": [{\"Title\": \"Member of the Order of the Phoenix\",\"Company Name\": \"Order of the Phoenix\",\"Starting Year\": \"1980\",\"Ending Year\": \"1995\"}],\"Certifications\": [\"Combat Training Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_11",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Draco Malfoy\",\"Email\": \"draco@email.com\",\"Phone\": \"+1 (678) 901-2345\",\"City\": \"Malfoy Manor\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 5,\"Tech Skills\": [\"Potion-making\", \"Duelling\", \"Dark Arts\", \"Slytherin House Leadership\"],\"Soft Skills\": [\"Ambition\", \"Resourcefulness\", \"Elegance\"],\"Recommended Roles\": [\"Potioneer\", \"Heir to the Malfoy Family\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1998\"}],\"Experience\": [{\"Title\": \"Potioneer\",\"Company Name\": \"Borgin and Burkes\",\"Starting Year\": \"2000\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Advanced Potions Mastery Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_12",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Ron Weasley\",\"Email\": \"ron@email.com\",\"Phone\": \"+1 (345) 678-9012\",\"City\": \"Ottery St. Catchpole\",\"State\": \"England\",\"Country\": \"United Kingdom\",\"YoE\": 3,\"Tech Skills\": [\"Chess\", \"Flying\", \"Cooking\", \"Wizardry\"],\"Soft Skills\": [\"Loyalty\", \"Adaptability\", \"Bravery\"],\"Recommended Roles\": [\"Auror\", \"Weasley's Wizard Wheezes Employee\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"2001\"}],\"Experience\": [{\"Title\": \"Auror Trainee\",\"Company Name\": \"Ministry of Magic\",\"Starting Year\": \"2001\",\"Ending Year\": \"2003\"},{\"Title\": \"Co-owner\",\"Company Name\": \"Weasley's Wizard Wheezes\",\"Starting Year\": \"2003\",\"Ending Year\": \"Present\"}],\"Certifications\": [\"Auror Trainee Certification\", \"Entrepreneurship Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_13",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Bellatrix Lestrange\",\"Email\": \"bellatrix@email.com\",\"Phone\": \"+1 (901) 234-5678\",\"City\": \"Azkaban\",\"State\": \"None\",\"Country\": \"None\",\"YoE\": 20,\"Tech Skills\": [\"Dark Arts\", \"Unforgivable Curses\", \"Dueling\"],\"Soft Skills\": [\"Loyalty to Lord Voldemort\", \"Cruelty\", \"Fanaticism\"],\"Recommended Roles\": [\"Dark Witch\", \"Death Eater\"],\"Education\": [{\"Institute\": \"Self-taught\",\"Qualification\": \"Dark Arts Mastery\",\"CompletionYear\": \"Unknown\"}],\"Experience\": [{\"Title\": \"Death Eater\",\"Company Name\": \"Lord Voldemort's Service\",\"Starting Year\": \"1970\",\"Ending Year\": \"1998\"}],\"Certifications\": [\"Unforgivable Curses Mastery\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_14",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Remus Lupin\",\"Email\": \"remus@email.com\",\"Phone\": \"+1 (234) 567-8901\",\"City\": \"Hogsmeade\",\"State\": \"Scotland\",\"Country\": \"United Kingdom\",\"YoE\": 10,\"Tech Skills\": [\"Defense Against the Dark Arts\", \"Lycanthropy Management\", \"Teaching\"],\"Soft Skills\": [\"Empathy\", \"Patience\", \"Mentoring\"],\"Recommended Roles\": [\"Defense Against the Dark Arts Professor\", \"Order of the Phoenix Member\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"1978\"}],\"Experience\": [{\"Title\": \"Defense Against the Dark Arts Professor\",\"Company Name\": \"Hogwarts School of Witchcraft and Wizardry\",\"Starting Year\": \"1993\",\"Ending Year\": \"1994\"}],\"Certifications\": [\"Teaching Certification\"],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
  {
    id: "hogwarts_15",
    aiGeneratedPersona: "",
    manuallyCreatedPersona: "{\"Name\": \"Rubeus Hagrid\",\"Email\": \"hagrid@email.com\",\"Phone\": \"+1 (456) 789-0123\",\"City\": \"Hogsmeade\",\"State\": \"Scotland\",\"Country\": \"United Kingdom\",\"YoE\": 30,\"Tech Skills\": [\"Magical Creatures Care\", \"Groundskeeping\", \"Love for Magical Beasts\"],\"Soft Skills\": [\"Compassion\", \"Loyalty\", \"Bravery\"],\"Recommended Roles\": [\"Keeper of Keys and Grounds at Hogwarts\", \"Magical Creatures Caretaker\"],\"Education\": [{\"Institute\": \"Hogwarts School of Witchcraft and Wizardry\",\"Qualification\": \"Wizardry\",\"CompletionYear\": \"Unknown\"}],\"Experience\": [{\"Title\": \"Keeper of Keys and Grounds\",\"Company Name\": \"Hogwarts School of Witchcraft and Wizardry\",\"Starting Year\": \"1950\",\"Ending Year\": \"Present\"}],\"Certifications\": [],\"BuiltBy\":\"HUMAN\"}",
    fileUploadId: "",
    updatedAt: {seconds: "1693976555", nanos: 999000000},
  },
]
